services:
  app:
    image: nexo-pos:latest
    container_name: nexo_app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mariadb
      - DB_PORT=3307
      - DB_DATABASE=nexopos
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_CONNECTION=mariadb
#      - APP_KEY=base64:z4AlJfYIEZAzsOXAlTDvTDVKENc6hS3dqcMhFJpkfl0=
      - QUEUE_CONNECTION=redis
    ports:
      - "9000:9000"
    volumes:
      - nexo_data:/var/www/html:Z
    networks:
      - nexo
  webserver:
    image: nginx:latest
    container_name: nexopos_webserver
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - nexo_data:/var/www/html:Z
    ports:
      - "8080:80"
    networks:
      - nexo

  mariadb:
    image: mariadb:latest
    container_name: laravel_db
    environment:
      - MYSQL_USER=nexopos_user
      - MYSQL_PASSWORD=laravel
      - MYSQL_DATABASE=nexopos
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - nexo

  redis:
    image: redis:alpine
    container_name: nexopos_redis

  queue:
    image: nexo-pos:latest
    container_name: nexopos_queue
    command: php artisan queue:work
    volumes:
      - nexo_data:/var/www/html:Z
    depends_on:
      - redis
      - mariadb
    networks:
      - nexo

volumes:
  db_data:
  nexo_data:
networks:
  nexo:
    driver: bridge

